---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: install apt packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - graphite-web
    - graphite-carbon
