---
- name: install apache
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apache2
    - libapache2-mod-wsgi
- name: disable default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload apache
- name: install graphite-web site
  template:
    src: apache2-graphite.conf.j2
    dest: /etc/apache2/sites-enabled/graphite.conf
  notify: reload apache
